version: "3.9"

services:
  backend:
    build: ./backend
    container_name: my_backend
    restart: always
    ports:
      - "8080:8080"
   

  frontend:
    build: ./frontend
    container_name: my_frontend
    restart: always
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend


